#  deploy:
#    runs-on: ubuntu-latest
#    needs: train

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v2
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1  # Specify your AWS region

#    - name: Update Kubeconfig
#      run: |
#        aws eks update-kubeconfig --name my-cluster

#    - name: Deploy to EKS
#      run: |
#        kubectl apply -f k8s/deployment.yaml  # Update the path to your Kubernetes manifest

