name: MLOps Continuous Deployment

on:
  push:
    branches:
      - develop           # Trigger deployment on push to the develop branch
    paths:
      - '**'                        # Trigger deployment for any change in the repository
      - 'mlops-final-project/**'    # Trigger workflow for changes in this directory            

env:
  AWS_DEFAULT_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
  ECR_REPOSITORY: mlops-final-project
  IMAGE_TAG: ${{ github.sha }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Deploy to EKS
      run: |
          kubectl apply -f /04-deployment/web-service/model-deployment.yaml

